x = degtorad(24)

equal_to = @(x, y) abs(x - y) <= eps;            %Сравнение двух значений с плавающей точкой

first_is_right = equal_to( ...
   tan(3 * x), ...
   (3 * tan(x) - tan(x)^3) / (1 - 3 * tan(x)^2) ...
)

second_is_right =  equal_to( ...
    cos(4 * x), ...
    8 * (cos(x)^4 - cos(x)^2) + 1 ...
)